services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    hostname: wg-easy-server
    container_name: wg-easy
    privileged: true
    env_file:
      - ./.env
    volumes:
      - ~/.config/.wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    ports:
#       - 51821:51821/tcp
       - 51820:51820/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg-easy.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.wg-easy.entrypoints=web, websecure
      - traefik.http.routers.wg-easy.tls=true
      - traefik.http.routers.wg-easy.tls.certresolver=letsencrypt
      - traefik.http.services.wg-easy.loadBalancer.server.port=51821
#      - traefik.udp.routers.wg-router.entrypoints=wireguard  # Use the 'wireguard' entrypoint
#      - traefik.udp.routers.wg-router.service=wg-service  # Link to the wg-service
#      - traefik.udp.services.wg-service.loadbalancer.server.port=51820  # Internal UDP port exposed by wg-easy
    healthcheck:
      test:
        - CMD
        - wg
        - show
        - wg0
        - dump
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 20s
    dns:
      - 1.1.1.1  # Cloudflare DNS
      - 8.8.8.8  # Google DNS
    networks:
      - wg-easy-network

networks:
  wg-easy-network:
    external: true
